[influx]
database = "prod"
host = "1.2.3.1"
password = "<YOUR PASSWORD>"
port = "8086"
user = "influx"

[mqtt]
ca_cert = "ca.crt"
host = "1.2.3.2"
port = "1883"
private_key = "server.key"
server_cert = "server.crt"

[sock]
path = "/tmp/pyrinas.sock"

[s3]
access_key = "<YOUR ACCESS KEY>"
bucket = "<BUCKET NAME>"
region = "us-east-1"
secret_key = "<YOUR SECRET KEY>"

[sled]
path = "./sled.db"
