server_url = "test.jaredwolff.com"

[influx]
database = "<DATABASE NAME>"
host = "<IP>"
password = "<PASSWORD>"
port = 8086
user = "<USER>"

[mqtt]
id = "<YOUR SERVER NAME>"
ca_cert = "ca.crt"
host = "<IP>"
port = 1883
private_key = "rust-server.key"
server_cert = "rust-server.crt"

[sock]
path = "/tmp/pyrinas.sock"

[ota]
db_path = "./sled.db"
http_port = 3030
