[package]
authors = ["Jared Wolff <hello@jaredwolff.com>"]
edition = "2018"
name = "pyrinas-server"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-creds = "^0.22.2" 
aws-region = "^0.21.0" 
diesel = {version = "^1.4.4", features = ["sqlite", "chrono"]}# ORM for database work 
diesel_migrations = "^1.4.0" # Automatic diesel migrations when starting the app
dotenv = "^0.9.0" # .env file parsing
env_logger = "^0.7" # logging message control using env variable
influxdb = {path = "../../../influxdb-rust/influxdb/", features = ["derive"]}# InfluxDB access 
log = "^0.4.11" # logging messages
rumqttc = {git = "https://github.com/bytebeamio/rumqtt"}# Mqtt core bits 
rust-s3 = "^0.22.12" # Handling upload of files
serde = {version = "^1.0", features = ["derive"]}# Serializing/deserializing 
serde_cbor = "^0.11.0" # Serde specific CBOR serialize/deserialze
serde_derive = "^1.0" # Serializing/deserializing structs
serde_json = "^1.0" # Serializing/deserializing json
sled = "^0.34.0" # Storing events as KV store
tokio = {version = "0.2.22", features = ["uds", "io-util"]} 

[dependencies.pyrinas-shared]
path = "../lib-shared/"

# Web library -- for handling requests from APP
