[package]
authors = ["Jared Wolff <hello@jaredwolff.com>"]
edition = "2018"
name = "pyrinas-server"
version = "0.1.0"
license = "Apache-2.0"

[features]
default = ["runtime_tokio"]
runtime_tokio = ["tokio", "tokio-stream"]
runtime_async_std = ["async-std", "async-macros"]

[dependencies]
async-channel = "1.5.1" # Used with rumqttc
clap = "3.0.0-beta.2" # CLI Library
env_logger = "0.8" # logging message control using env variable
influxdb = { version = "0.3", features = ["derive"] }# InfluxDB access 
log = "0.4" # logging messages
pyrinas-shared = { path = "../lib-shared/" }# Local shared for settings, etc 
rumqttc = "0.2" # Mqtt core bits 
rust-s3 = "0.26" # Handling upload of files
serde = { version = "1.0", features = ["derive"] }# Serializing/deserializing 
serde_cbor = "0.11" # Serde specific CBOR serialize/deserialze
serde_json = "1.0" # Serializing/deserializing json
sled = "0.34" # Storing events as KV store
flume = "0.10.2" # Channels
cfg-if = "1.0.0" # Macro config
anyhow = "1.0" # Generic error

# Optional features
tokio = { version = "1.0", default-features = false, features = ["net", "rt", "macros", "io-util"], optional = true }
async-std = { version = "1.9.0", optional = true, default-features = false }
async-macros = { version = "2.0.0", optional = true }
tokio-stream = { version = "*", features = ["net"], optional = true }
