[package]
authors = ["Jared Wolff <hello@jaredwolff.com>"]
edition = "2018"
name = "pyrinas-server"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "^1.6.2" # For async functions
diesel = {version = "^1.4.4", features = ["sqlite", "chrono"]}# ORM for database work 
diesel_migrations = "^1.4.0" # Automatic diesel migrations when starting the app
dotenv = "^0.9.0" # .env file parsing
env_logger = "^0.7" # logging message control using env variable
futures = {version = "0.3", features = ["compat"]}# used along side tokio for async operations 
futures-timer = "0.3" # same as above
influxdb = {version = "^0.1.0", features = ["derive"]}# InfluxDB access 
log = "^0.4.11" # logging messages
paho-mqtt = {git = "https://github.com/eclipse/paho.mqtt.rust", features = ["build_bindgen"]}# MQTT library -- does have dependencies on local paho c install 
serde = {version = "^1.0", features = ["derive"]}# Serializing/deserializing 
serde_cbor = "^0.11.0" # Serde specific CBOR serialize/deserialze
serde_derive = "^1.0" # Serializing/deserializing
sled = "^0.34.0" # Storing events as KV store
tokio = "^0.2.21" # Async functions for parallel operations, message passing, etc

[dependencies.pyrinas-shared]
path = "../lib-shared/"

[dev-dependencies]
async-std = "1"

# Web library -- for handling requests from APP
