[package]
authors = ["Jared Wolff <hello@jaredwolff.com>"]
edition = "2018"
name = "pyrinas-server"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2" # CLI Library
env_logger = "0.8" # logging message control using env variable
influxdb = {git = "https://github.com/Empty2k12/influxdb-rust", rev = "056681190af7535daccbf24fe04b06f770733f5a", features = ["derive"]}# InfluxDB access 
log = "0.4" # logging messages
pyrinas-shared = {path = "../lib-shared/"}# Local shared for settings, etc 
rumqttc = {git = "https://github.com/bytebeamio/rumqtt", rev = "2121d7fb"}# Mqtt core bits 
rust-s3 = "0.26" # Handling upload of files
serde = {version = "1.0", features = ["derive"]}# Serializing/deserializing 
serde_cbor = "0.11" # Serde specific CBOR serialize/deserialze
serde_json = "1.0" # Serializing/deserializing json
sled = "0.34" # Storing events as KV store
tokio = {version = "0.2.22", features = ["uds", "io-util"]}
