[package]
authors = ["Jared Wolff <hello@jaredwolff.com>"]
edition = "2018"
name = "pyrinas-cli"
version = "0.1.0"

[dependencies]
aws-creds = "^0.22.2" # AWS related
aws-region = "^0.21.0" # AWS related
chrono = "^0.4.0" # Tracking time
clap = "~3.0.0-beta.1" # CLI Library (Needed?)
dotenv = "^0.9.0" # .env file parsing
env_logger = "^0.7" # logging message control using env variable
log = "^0.4.11" # logging messages
pyrinas-shared = { path = "../lib-shared/" } 
rust-s3 = "^0.22.12" # Handling upload of files
serde = { version = "^1.0", features = ["derive"] }# Serializing/deserializing  
serde_json = "^1.0" # For serialization of json
serde_cbor = "^0.11.0" # Serde specific CBOR serialize/deserialze
