[package]
authors = ["Jared Wolff <hello@jaredwolff.com>"]
edition = "2018"
name = "pyrinas-shared"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.6"
chrono = "0.4.13"
influxdb = {path = "../../../influxdb-rust/influxdb/", features = ["derive"]}# InfluxDB access
serde = {version = "^1.0", features = ["derive"]}# Serializing/deserializing
serde_repr = "0.1"
tokio = "0.2.22"
