[package]
authors = ["Jared Wolff <hello@jaredwolff.com>"]
edition = "2018"
name = "pyrinas-shared"
version = "0.2.0"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
influxdb = { version = "0.3", features = ["derive"] }# InfluxDB access
serde = { version = "1.0", features = ["derive"] }# Serializing/deserializing
serde_repr = "0.1"
toml = "0.5"
anyhow = "1.0"
flume = "0.10.2"
rumqttd = { git = "https://github.com/bytebeamio/rumqtt", rev = "cd8cafe3ecdebe614fd5f0dd002197fa54082008" }# Mqtt core bits
